# -*- coding: utf-8 -*-
"""CountVectorizer_decisiontree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hrJNRwZsPCfBSStZljkb5tYAuVuhwN7
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

# 1. Load data
train_df = pd.read_csv('/content/drive/MyDrive/Learning/DSAI4205/traindata7.csv')
test_df = pd.read_csv('/content/drive/MyDrive/Learning/DSAI4205/testdata7.csv')

X_train = train_df['Phrase']
y_train = train_df['Sentiment']

X_test = test_df['Phrase']
y_test = test_df['Sentiment']

from sklearn.feature_extraction.text import CountVectorizer

# 2. Text Embedding (CountVectorizer)
vectorizer = CountVectorizer(
    stop_words='english',
    min_df=3,
    max_features=3000,
    ngram_range=(1,1)
)

X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

# 3. Train Decision Tree
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train_vectorized, y_train)

# 4. Predictions
train_pred = clf.predict(X_train_vectorized)
test_pred = clf.predict(X_test_vectorized)

# 5. Accuracy
train_accuracy = accuracy_score(y_train, train_pred)
test_accuracy = accuracy_score(y_test, test_pred)

# 6. "Loss" – classification error rate
train_loss = 1 - train_accuracy
test_loss = 1 - test_accuracy

# 7. Print results
print("Training Accuracy:", train_accuracy)
print("Training Loss (Error):", train_loss)
print("Testing Accuracy:", test_accuracy)
print("Testing Loss (Error):", test_loss)